// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADmwRxaIN1Nay1SY0ENUPZ5jk3tEqDy04',
    appId: '1:241936653826:web:77ded49a687e9c9dfc911b',
    messagingSenderId: '241936653826',
    projectId: 'lazaapp-fe181',
    authDomain: 'lazaapp-fe181.firebaseapp.com',
    storageBucket: 'lazaapp-fe181.firebasestorage.app',
    measurementId: 'G-EVXPGDKP27',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuWFqEvUqY7omfZZ7EI32IKZMx-CIXLkw',
    appId: '1:241936653826:android:63e71ab4214ae783fc911b',
    messagingSenderId: '241936653826',
    projectId: 'lazaapp-fe181',
    storageBucket: 'lazaapp-fe181.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgqix2C9GLGfZqPTN-_H4TW43xsepmi34',
    appId: '1:241936653826:ios:2238e6ffcc9e51b5fc911b',
    messagingSenderId: '241936653826',
    projectId: 'lazaapp-fe181',
    storageBucket: 'lazaapp-fe181.firebasestorage.app',
    iosBundleId: 'lazaapp-fe181',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgqix2C9GLGfZqPTN-_H4TW43xsepmi34',
    appId: '1:241936653826:ios:2238e6ffcc9e51b5fc911b',
    messagingSenderId: '241936653826',
    projectId: 'lazaapp-fe181',
    storageBucket: 'lazaapp-fe181.firebasestorage.app',
    iosBundleId: 'lazaapp-fe181',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADmwRxaIN1Nay1SY0ENUPZ5jk3tEqDy04',
    appId: '1:241936653826:web:a2cdd99d611d0295fc911b',
    messagingSenderId: '241936653826',
    projectId: 'lazaapp-fe181',
    authDomain: 'lazaapp-fe181.firebaseapp.com',
    storageBucket: 'lazaapp-fe181.firebasestorage.app',
    measurementId: 'G-KFD5HRR415',
  );
}
